import type { Linter } from 'eslint';
import pluginAstro from 'eslint-plugin-astro';
import pluginUnicorn from 'eslint-plugin-unicorn';

const config: Linter.Config[] = [
  ...(pluginAstro.configs.recommended as Linter.Config[]),
  pluginUnicorn.configs.recommended as Linter.Config,
  {
    // Astro uses PascalCase for component filenames by convention.
    // Also applies to virtual script blocks (*.astro/*.tsx) generated by eslint-plugin-astro.
    files: ['**/*.astro', '**/*.astro/*.tsx', '**/*.astro/*.ts'],
    rules: {
      'unicorn/filename-case': ['error', { cases: { pascalCase: true, kebabCase: true } }],
      // Props/Properties interfaces are used implicitly via Astro.props typing
      '@typescript-eslint/no-unused-vars': ['error', { varsIgnorePattern: '^Properties$' }],
    },
  } as Linter.Config,
];

export default config;
