design-tokens: "./design-system/design-tokens/**"
css: "./design-system/css/**"
components: "./design-system/components/**"
ai-context-sync: "./packages/ai-context-sync/**"
react-components: "./packages/react-components/**"
react-hooks: "./packages/react-hooks/**"
scaffolding: "./packages/scaffolding/**"
types: "./packages/types/**"
eslint-config-ts-base: "./configs/eslint-config-ts-base/**"
eslint-plugin-web: "./linters/eslint-plugin-web/**"
