import fs from 'node:fs/promises';
import path from 'node:path';
import { optimize } from 'svgo';

const SVG_DIR = path.resolve('src/svg');
const REACT_DIR = path.resolve('src/react');
const ICONS_FILE = path.resolve('src/icons.ts');

/** Convert kebab-case filename (without extension) to PascalCase component name */
function toPascalCase(kebab: string): string {
  return kebab
    .split('-')
    .map(segment => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('');
}

/** Extract the inner SVG content (everything inside the root <svg> element) */
function extractInnerSvg(optimizedSvg: string): string {
  const match = optimizedSvg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  return match ? match[1].trim() : '';
}

/** Map of SVG attribute names to their JSX equivalents */
const SVG_ATTR_MAP: Record<string, string> = {
  'stroke-width': 'strokeWidth',
  'stroke-linecap': 'strokeLinecap',
  'stroke-linejoin': 'strokeLinejoin',
  'fill-rule': 'fillRule',
  'clip-rule': 'clipRule',
  'clip-path': 'clipPath',
  'stop-color': 'stopColor',
  'stop-opacity': 'stopOpacity',
  'font-size': 'fontSize',
  'font-family': 'fontFamily',
  'text-anchor': 'textAnchor',
  'dominant-baseline': 'dominantBaseline',
};

/** Convert SVG attribute string to JSX-compatible attributes */
function toJsxAttrs(attrs: string): string {
  return attrs.replace(/(\S+?)=/g, (_, attr) => {
    return (SVG_ATTR_MAP[attr] ?? attr) + '=';
  });
}

/** Extract all attributes from the root <svg> element except xmlns, one per line */
function extractSvgAttrs(optimizedSvg: string): string {
  const match = optimizedSvg.match(/<svg([^>]*)>/);
  if (!match) return '';
  const raw = match[1]
    .replace(/\s*xmlns="[^"]*"/, '')
    .trim();
  const jsxAttrs = toJsxAttrs(raw);
  // Split attr string into individual attr="value" tokens and put each on its own line
  const tokens = jsxAttrs.match(/\S+="[^"]*"/g) ?? [];
  return tokens.join('\n      ');
}

async function buildIcons(): Promise<void> {
  // Ensure output directory exists
  await fs.mkdir(REACT_DIR, { recursive: true });

  const files = (await fs.readdir(SVG_DIR)).filter(f => f.endsWith('.svg'));
  files.sort();

  const exports: { name: string; kebab: string }[] = [];

  for (const file of files) {
    const kebab = file.replace(/\.svg$/, '');
    const name = toPascalCase(kebab);
    const raw = await fs.readFile(path.join(SVG_DIR, file), 'utf-8');

    const result = optimize(raw, {
      plugins: [
        {
          name: 'preset-default',
          params: {
            overrides: {
              // convertColors is part of preset-default — disable to keep currentColor
              convertColors: false,
            },
          },
        },
        // removeViewBox must be listed outside preset-default overrides to disable it
        { name: 'removeViewBox', active: false },
        {
          name: 'removeAttrs',
          params: { attrs: ['svg:width', 'svg:height'] },
        },
      ],
    });

    const optimized = result.data;
    const innerSvg = extractInnerSvg(optimized);
    const sq = '\x27';
    const innerSvgEscaped = innerSvg.replace(/\\/g, '\\\\').replace(/'/g, `\\${sq}`);
    const svgAttrs = extractSvgAttrs(optimized);

    const component = `import type { SVGProps } from 'react';

interface ${name}Props extends SVGProps<SVGSVGElement> {
  label?: string;
}

export function ${name}({ label, style, ...props }: ${name}Props) {
  return (
    <svg
      ${svgAttrs}
      aria-hidden={label ? undefined : true}
      aria-label={label}
      role={label ? 'img' : undefined}
      style={{ width: 'var(--icon-size, 1em)', height: 'var(--icon-size, 1em)', ...style }}
      {...props}
      dangerouslySetInnerHTML={{ __html: '${innerSvgEscaped}' }}
    />
  );
}
`;

    await fs.writeFile(path.join(REACT_DIR, `${name}.tsx`), component, 'utf-8');
    exports.push({ name, kebab });
    console.log(`  ✓ ${file} → ${name}.tsx`);
  }

  // Emit barrel index
  const barrel = exports.map(({ name }) => `export { ${name} } from './${name}.js';`).join('\n') + '\n';
  await fs.writeFile(path.join(REACT_DIR, 'index.ts'), barrel, 'utf-8');

  // Emit IconName union type
  const [first, ...rest] = exports.map(({ kebab }) => kebab);
  const restLines = rest.map(kebab => `    | '${kebab}'`).join('\n');
  const iconsTs = `// Auto-generated by scripts/build-icons.ts — do not edit manually\nexport type IconName\n  = '${first}'\n${restLines};\n`;
  await fs.writeFile(ICONS_FILE, iconsTs, 'utf-8');

  console.log(`\nGenerated ${exports.length} icons → src/react/`);
  console.log('Generated src/icons.ts');
}

buildIcons().catch((err) => {
  console.error(err);
  process.exit(1);
});
