name: Setup JS
description: Configure JS environment and dependencies
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Setup node
      uses: actions/setup-node@v5
      with:
        node-version: 22
        cache: "pnpm"
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
