name: Setup JS
description: Configure JS environment and dependencies
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v5
      with:
        node-version: 22
    - name: Install dependencies
      uses: pnpm/action-setup@v4
      with:
        version: 10
