import type { Linter, Rule } from 'eslint';
import tsBase from '@dezkareid/eslint-config-ts-base';
import reactPlugin from '@eslint-react/eslint-plugin';
import pluginAstro from 'eslint-plugin-astro';
import pluginUnicorn from 'eslint-plugin-unicorn';
import noJquery from './rules/no-jquery.js';
import noAllowedPackages from './rules/no-allowed-packages.js';

export const meta = {
  name: '@dezkareid/eslint-plugin-web',
  version: '0.0.0',
};

export const rules = {
  'no-jquery': noJquery,
  'no-allowed-packages': noAllowedPackages,
};

export const configs: Record<string, Linter.Config[]> = {
  typescript: tsBase as Linter.Config[],
  react: [
    reactPlugin.configs.recommended as Linter.Config,
    pluginUnicorn.configs.recommended as Linter.Config,
  ],
  astro: [
    ...(pluginAstro.configs.recommended as Linter.Config[]),
    pluginUnicorn.configs.recommended as Linter.Config,
    {
      // Astro uses PascalCase for component filenames by convention.
      // Also applies to virtual script blocks (*.astro/*.tsx) generated by eslint-plugin-astro.
      files: ['**/*.astro', '**/*.astro/*.tsx', '**/*.astro/*.ts'],
      rules: {
        'unicorn/filename-case': ['error', { cases: { pascalCase: true, kebabCase: true } }],
        // Props/Properties interfaces are used implicitly via Astro.props typing
        '@typescript-eslint/no-unused-vars': ['error', { varsIgnorePattern: '^Properties$' }],
      },
    } as Linter.Config,
  ],
};

const plugin: {
  meta: typeof meta;
  rules: Record<string, Rule.RuleModule>;
  configs: Record<string, Linter.Config[]>;
} = { meta, rules, configs };

export default plugin;
